
package xqbhserver.servertran;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CommonTranService", targetNamespace = "http://ServerTran.XQBHServer/", wsdlLocation = "META-INF/wsdl/CommonTranService.wsdl")
public class CommonTranService
    extends Service
{

    private final static URL COMMONTRANSERVICE_WSDL_LOCATION;
    private final static WebServiceException COMMONTRANSERVICE_EXCEPTION;
    private final static QName COMMONTRANSERVICE_QNAME = new QName("http://ServerTran.XQBHServer/", "CommonTranService");

    static {
        COMMONTRANSERVICE_WSDL_LOCATION = xqbhserver.servertran.CommonTranService.class.getClassLoader().getResource("META-INF/wsdl/CommonTranService.wsdl");
        WebServiceException e = null;
        if (COMMONTRANSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/CommonTranService.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        COMMONTRANSERVICE_EXCEPTION = e;
    }

    public CommonTranService() {
        super(__getWsdlLocation(), COMMONTRANSERVICE_QNAME);
    }

    public CommonTranService(WebServiceFeature... features) {
        super(__getWsdlLocation(), COMMONTRANSERVICE_QNAME, features);
    }

    public CommonTranService(URL wsdlLocation) {
        super(wsdlLocation, COMMONTRANSERVICE_QNAME);
    }

    public CommonTranService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COMMONTRANSERVICE_QNAME, features);
    }

    public CommonTranService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CommonTranService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CommonTran
     */
    @WebEndpoint(name = "CommonTranPort")
    public CommonTran getCommonTranPort() {
        return super.getPort(new QName("http://ServerTran.XQBHServer/", "CommonTranPort"), CommonTran.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CommonTran
     */
    @WebEndpoint(name = "CommonTranPort")
    public CommonTran getCommonTranPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ServerTran.XQBHServer/", "CommonTranPort"), CommonTran.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COMMONTRANSERVICE_EXCEPTION!= null) {
            throw COMMONTRANSERVICE_EXCEPTION;
        }
        return COMMONTRANSERVICE_WSDL_LOCATION;
    }

}
