
package CommonTran;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CommonTran", targetNamespace = "http://ServerTran/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CommonTran {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Comtran")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Comtran", targetNamespace = "http://ServerTran/", className = "CommonTran.Comtran")
    @ResponseWrapper(localName = "ComtranResponse", targetNamespace = "http://ServerTran/", className = "CommonTran.ComtranResponse")
    @Action(input = "http://ServerTran/CommonTran/ComtranRequest", output = "http://ServerTran/CommonTran/ComtranResponse")
    public String comtran(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOut", targetNamespace = "http://ServerTran/", className = "CommonTran.GetOut")
    @ResponseWrapper(localName = "getOutResponse", targetNamespace = "http://ServerTran/", className = "CommonTran.GetOutResponse")
    @Action(input = "http://ServerTran/CommonTran/getOutRequest", output = "http://ServerTran/CommonTran/getOutResponse")
    public String getOut(
        @WebParam(name = "arg0", targetNamespace = "")
        TranObj arg0);

}
